// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC34JYjzIpyjjQtWZr-KC5QVOuoRq_w_-Y',
    appId: '1:290902738902:web:96b903611ca4d7b0534677',
    messagingSenderId: '290902738902',
    projectId: 'swapngive',
    authDomain: 'swapngive.firebaseapp.com',
    storageBucket: 'swapngive.appspot.com',
    measurementId: 'G-TVBXH9JV2B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC0L0B_bdCR5GQL1wdyHAEYYhfgOt9Wsnw',
    appId: '1:290902738902:android:a47b8b52fddc5385534677',
    messagingSenderId: '290902738902',
    projectId: 'swapngive',
    storageBucket: 'swapngive.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDnhWuZiyo4qIWwFCesLDsjIJw00vGky4Y',
    appId: '1:290902738902:ios:a3b0611e01c0f9b9534677',
    messagingSenderId: '290902738902',
    projectId: 'swapngive',
    storageBucket: 'swapngive.appspot.com',
    iosBundleId: 'com.example.swapngive',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDnhWuZiyo4qIWwFCesLDsjIJw00vGky4Y',
    appId: '1:290902738902:ios:a3b0611e01c0f9b9534677',
    messagingSenderId: '290902738902',
    projectId: 'swapngive',
    storageBucket: 'swapngive.appspot.com',
    iosBundleId: 'com.example.swapngive',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC34JYjzIpyjjQtWZr-KC5QVOuoRq_w_-Y',
    appId: '1:290902738902:web:87f5b7360e052db2534677',
    messagingSenderId: '290902738902',
    projectId: 'swapngive',
    authDomain: 'swapngive.firebaseapp.com',
    storageBucket: 'swapngive.appspot.com',
    measurementId: 'G-BHYR998TGJ',
  );
}
